import type { Product } from "@/types/domain";

// 12-product seed portfolio (distribution from the vision doc):
// 4 Healthy · 3 At Risk · 2 Over Budget · 1 Pending · 2 Archived.
// The first three map to the real portfolio execution engines.
export const PRODUCTS: Product[] = [
  {
    id: "ai-native-diagnostic",
    name: "AI-Native Team Diagnostic",
    status: "healthy",
    lifecycle: "production",
    architecture: "SaaS",
    businessUnit: "People & Enablement",
    owner: "S. Adeyemi",
    engLead: "R. Cho",
    sponsor: "VP, Transformation",
    monthlySpend: 1800,
    annualBudget: 30000,
    roi: 210,
    adoption: 82,
    sourceEngine: "ai-native-diagnostic",
    summary:
      "Self-scoring assessment that measures a team's AI-native readiness across capability dimensions.",
  },
  {
    id: "enterprise-rag",
    name: "Enterprise RAG Assistant",
    status: "healthy",
    lifecycle: "production",
    architecture: "RAG",
    businessUnit: "Knowledge & Support",
    owner: "S. Adeyemi",
    engLead: "M. Okafor",
    sponsor: "Head of Support",
    monthlySpend: 2400,
    annualBudget: 42000,
    roi: 168,
    adoption: 74,
    sourceEngine: "enterprise-rag",
    summary:
      "Grounded retrieval assistant over a curated knowledge base with citation-level traceability and eval gating.",
  },
  {
    id: "financial-intelligence",
    name: "Financial Intelligence Strategy Agent",
    status: "healthy",
    lifecycle: "production",
    architecture: "Agentic",
    businessUnit: "Strategy & Finance",
    owner: "S. Adeyemi",
    engLead: "L. Tremblay",
    sponsor: "CFO Office",
    monthlySpend: 900,
    annualBudget: 18000,
    roi: 260,
    adoption: 61,
    sourceEngine: "financial-intelligence",
    summary:
      "Autonomous BI agent producing demographic-to-strategy briefs from live public financial data sources.",
  },
  {
    id: "contract-copilot",
    name: "Contract Review Copilot",
    status: "healthy",
    lifecycle: "production",
    architecture: "Hybrid",
    businessUnit: "Legal",
    owner: "D. Nwosu",
    engLead: "P. Sharma",
    sponsor: "General Counsel",
    monthlySpend: 5200,
    annualBudget: 72000,
    roi: 140,
    adoption: 69,
    summary: "Clause extraction and risk-flagging assistant for inbound commercial contracts.",
  },
  {
    id: "demand-forecaster",
    name: "Demand Forecasting Engine",
    status: "at-risk",
    lifecycle: "pilot",
    architecture: "Fine-Tuning",
    businessUnit: "Supply Chain",
    owner: "K. Mensah",
    engLead: "J. Alvarez",
    sponsor: "COO",
    monthlySpend: 6100,
    annualBudget: 60000,
    roi: 55,
    adoption: 38,
    summary: "Time-series model forecasting SKU-level demand; accuracy regressed after seasonality shift.",
  },
  {
    id: "support-triage",
    name: "Support Triage Classifier",
    status: "at-risk",
    lifecycle: "production",
    architecture: "Foundation Model",
    businessUnit: "Knowledge & Support",
    owner: "M. Okafor",
    engLead: "T. Bello",
    sponsor: "Head of Support",
    monthlySpend: 3300,
    annualBudget: 40000,
    roi: 88,
    adoption: 57,
    summary: "Routes inbound tickets to queues; drift in category mix is eroding routing precision.",
  },
  {
    id: "sales-agent",
    name: "Sales Outreach Agent",
    status: "at-risk",
    lifecycle: "pilot",
    architecture: "Agentic",
    businessUnit: "Revenue",
    owner: "A. Diallo",
    engLead: "C. Rossi",
    sponsor: "CRO",
    monthlySpend: 4700,
    annualBudget: 45000,
    roi: 42,
    adoption: 29,
    summary: "Drafts personalized outreach; adoption lagging on trust and human-oversight concerns.",
  },
  {
    id: "doc-summarizer",
    name: "Board Document Summarizer",
    status: "over-budget",
    lifecycle: "production",
    architecture: "Foundation Model",
    businessUnit: "Executive Office",
    owner: "D. Nwosu",
    engLead: "P. Sharma",
    sponsor: "Chief of Staff",
    monthlySpend: 9800,
    annualBudget: 84000,
    roi: 110,
    adoption: 71,
    summary: "Summarizes long board packs; premium-model token spend is running over plan.",
  },
  {
    id: "vision-qc",
    name: "Visual QC Inspector",
    status: "over-budget",
    lifecycle: "pilot",
    architecture: "Fine-Tuning",
    businessUnit: "Manufacturing",
    owner: "K. Mensah",
    engLead: "H. Yamada",
    sponsor: "VP Ops",
    monthlySpend: 11200,
    annualBudget: 96000,
    roi: 95,
    adoption: 44,
    summary: "Defect-detection vision model; GPU inference cost above the pilot envelope.",
  },
  {
    id: "hr-policy-bot",
    name: "HR Policy Assistant",
    status: "pending",
    lifecycle: "build",
    architecture: "RAG",
    businessUnit: "People & Enablement",
    owner: "S. Adeyemi",
    engLead: "R. Cho",
    sponsor: "CHRO",
    monthlySpend: 0,
    annualBudget: 24000,
    roi: 0,
    adoption: 0,
    summary: "Grounded HR-policy Q&A awaiting Responsible AI and privacy sign-off before pilot.",
  },
  {
    id: "legacy-chatbot",
    name: "Legacy FAQ Chatbot",
    status: "archived",
    lifecycle: "archived",
    architecture: "SaaS",
    businessUnit: "Knowledge & Support",
    owner: "M. Okafor",
    engLead: "T. Bello",
    sponsor: "Head of Support",
    monthlySpend: 0,
    annualBudget: 0,
    roi: 30,
    adoption: 12,
    summary: "First-generation rules chatbot; superseded by the Enterprise RAG Assistant.",
  },
  {
    id: "email-classifier",
    name: "Email Intent Classifier",
    status: "archived",
    lifecycle: "archived",
    architecture: "Fine-Tuning",
    businessUnit: "Revenue",
    owner: "A. Diallo",
    engLead: "C. Rossi",
    sponsor: "CRO",
    monthlySpend: 0,
    annualBudget: 0,
    roi: 60,
    adoption: 20,
    summary: "Legacy intent model retired after consolidation into the Sales Outreach Agent.",
  },
];

export const productById = (id: string) => PRODUCTS.find((p) => p.id === id);
